name: Build Server-Expansion
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build

      - name: Upload Server-Expansion Nightly
        uses: actions/upload-artifact@main
        with:
          name: Server-Expansion-Nightly
          path: build/libs/*.jar
